#!/usr/bin/env php
<?php declare(strict_types=1);
/*
 * This file is part of PHPUnit.
 *
 * (c) Sebastian Bergmann <sebastian@phpunit.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

if (version_compare('7.2.0', PHP_VERSION, '>')) {
    fwrite(
        STDERR,
        sprintf(
            'This version of think-core is supported on PHP 7.2 and PHP 7.3.' . PHP_EOL .
            'You are using PHP %s (%s).' . PHP_EOL,
            PHP_VERSION,
            PHP_BINARY
        )
    );

    die(1);
}

foreach (array(__DIR__ . '/../../../vendor/autoload.php', __DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('VENDOR_PATH', basename($file));

        break;
    }
}

unset($file);

if (!defined('VENDOR_PATH')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

if(!file_exists(VENDOR_PATH . "/../www/Public/libs")){
    symlink(VENDOR_PATH . "/tiderjian/think-core/asset/libs", VENDOR_PATH . "/../www/Public/libs");
    fwrite(STDOUT, "generate libs link finished!" . PHP_EOL);
}
else{
    fwrite(STDERR, "libs link already exists!" . PHP_EOL);
}

if(!is_dir(VENDOR_PATH . "/../www/Uploads")){
    @mkdir(VENDOR_PATH . "/../www/Uploads", 0666, true);
    fwrite(STDOUT, "create Uploads directory!" . PHP_EOL);
}
else{
    fwrite(STDERR, "Uploads directory already exists!" . PHP_EOL);
}

die(0);

