#!/usr/bin/env php
<?php declare(strict_types=1);
/*
 * This file is part of PHPUnit.
 *
 * (c) Sebastian Bergmann <sebastian@phpunit.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

if (version_compare('7.2.0', PHP_VERSION, '>')) {
    fwrite(
        STDERR,
        sprintf(
            'This version of think-core is supported on PHP 7.2 and PHP 7.3.' . PHP_EOL .
            'You are using PHP %s (%s).' . PHP_EOL,
            PHP_VERSION,
            PHP_BINARY
        )
    );

    die(1);
}

$dir = realpath('.');

foreach (array($dir . '/../autoload.php',$dir . '/../../../vendor/autoload.php', $dir . '/../../autoload.php', $dir . '/../vendor/autoload.php', $dir . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('VENDOR_PATH', dirname($file));

        break;
    }
}

unset($file);

if (!defined('VENDOR_PATH')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

if(!file_exists(VENDOR_PATH . "/../www/Public/libs")){
    include VENDOR_PATH . '/tiderjian/think-core/src/Library/Qscmf/Helper/function.php';
    $relative_path = getRelativePath(normalizeRelativePath(VENDOR_PATH . "/tiderjian/think-core/asset/libs"), normalizeRelativePath(VENDOR_PATH . "/../www/Public/libs"));
    symlink($relative_path, VENDOR_PATH . "/../www/Public/libs");
    fwrite(STDOUT, "generate libs link finished!" . PHP_EOL);
}
else{
    fwrite(STDERR, "libs link already exists!" . PHP_EOL);
}

die(0);

